apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/abhaysingh-oo7/devops-heros.git
    targetRevision: lec20
    path: session20-monitoring-observability-gitops/02-metrics-logs-traces/gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
